<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:15:02.
 */
class formularioResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var formularioResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new formularioResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers formularioResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::setModel
     * @todo   Implement testSetModel().
     */
    public function testSetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::execute
     * @todo   Implement testExecute().
     */
    public function testExecute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::genForm
     * @todo   Implement testGenForm().
     */
    public function testGenForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::executeAction
     * @todo   Implement testExecuteAction().
     */
    public function testExecuteAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::getForm
     * @todo   Implement testGetForm().
     */
    public function testGetForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::NewForm
     * @todo   Implement testNewForm().
     */
    public function testNewForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::closeform
     * @todo   Implement testCloseform().
     */
    public function testCloseform() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::setMethod
     * @todo   Implement testSetMethod().
     */
    public function testSetMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::printable
     * @todo   Implement testPrintable().
     */
    public function testPrintable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::omitir_cabecalho
     * @todo   Implement testOmitir_cabecalho().
     */
    public function testOmitir_cabecalho() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formularioResource::setFormTable
     * @todo   Implement testSetFormTable().
     */
    public function testSetFormTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
