<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:29.
 */
class FreteHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FreteHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FreteHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FreteHelper::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setService
     * @todo   Implement testSetService().
     */
    public function testSetService() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setZipFrom
     * @todo   Implement testSetZipFrom().
     */
    public function testSetZipFrom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setZipTo
     * @todo   Implement testSetZipTo().
     */
    public function testSetZipTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setItemWeight
     * @todo   Implement testSetItemWeight().
     */
    public function testSetItemWeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setItemForm
     * @todo   Implement testSetItemForm().
     */
    public function testSetItemForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setItemLength
     * @todo   Implement testSetItemLength().
     */
    public function testSetItemLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setItemHeight
     * @todo   Implement testSetItemHeight().
     */
    public function testSetItemHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setItemWidth
     * @todo   Implement testSetItemWidth().
     */
    public function testSetItemWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setItemDiameter
     * @todo   Implement testSetItemDiameter().
     */
    public function testSetItemDiameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setValor
     * @todo   Implement testSetValor().
     */
    public function testSetValor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::request
     * @todo   Implement testRequest().
     */
    public function testRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::getResult
     * @todo   Implement testGetResult().
     */
    public function testGetResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::getResultAsArray
     * @todo   Implement testGetResultAsArray().
     */
    public function testGetResultAsArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FreteHelper::getResultAsJavascript
     * @todo   Implement testGetResultAsJavascript().
     */
    public function testGetResultAsJavascript() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
