<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:15:06.
 */
class FormHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FormHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FormHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FormHelper::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setMethod
     * @todo   Implement testSetMethod().
     */
    public function testSetMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::Open
     * @todo   Implement testOpen().
     */
    public function testOpen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setCurrentForm
     * @todo   Implement testSetCurrentForm().
     */
    public function testSetCurrentForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::Close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::genValidation
     * @todo   Implement testGenValidation().
     */
    public function testGenValidation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getFormName
     * @todo   Implement testGetFormName().
     */
    public function testGetFormName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::flush
     * @todo   Implement testFlush().
     */
    public function testFlush() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setVars
     * @todo   Implement testSetVars().
     */
    public function testSetVars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setDados
     * @todo   Implement testSetDados().
     */
    public function testSetDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getDados
     * @todo   Implement testGetDados().
     */
    public function testGetDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getDado
     * @todo   Implement testGetDado().
     */
    public function testGetDado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getVars
     * @todo   Implement testGetVars().
     */
    public function testGetVars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getVar
     * @todo   Implement testGetVar().
     */
    public function testGetVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setVar
     * @todo   Implement testSetVar().
     */
    public function testSetVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::unsetVar
     * @todo   Implement testUnsetVar().
     */
    public function testUnsetVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::hasVar
     * @todo   Implement testHasVar().
     */
    public function testHasVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setModel
     * @todo   Implement testSetModel().
     */
    public function testSetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getModel
     * @todo   Implement testGetModel().
     */
    public function testGetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::SetCustomCamp
     * @todo   Implement testSetCustomCamp().
     */
    public function testSetCustomCamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setExternData
     * @todo   Implement testSetExternData().
     */
    public function testSetExternData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::setNNForm
     * @todo   Implement testSetNNForm().
     */
    public function testSetNNForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::text
     * @todo   Implement testText().
     */
    public function testText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::textarea
     * @todo   Implement testTextarea().
     */
    public function testTextarea() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::select
     * @todo   Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::radioCamp
     * @todo   Implement testRadioCamp().
     */
    public function testRadioCamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::radio
     * @todo   Implement testRadio().
     */
    public function testRadio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::checkCamp
     * @todo   Implement testCheckCamp().
     */
    public function testCheckCamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::checkbox
     * @todo   Implement testCheckbox().
     */
    public function testCheckbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::hidden
     * @todo   Implement testHidden().
     */
    public function testHidden() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::password
     * @todo   Implement testPassword().
     */
    public function testPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::file
     * @todo   Implement testFile().
     */
    public function testFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::FieldSet
     * @todo   Implement testFieldSet().
     */
    public function testFieldSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::CloseFieldSet
     * @todo   Implement testCloseFieldSet().
     */
    public function testCloseFieldSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::CloseAllFieldSets
     * @todo   Implement testCloseAllFieldSets().
     */
    public function testCloseAllFieldSets() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::ClearButton
     * @todo   Implement testClearButton().
     */
    public function testClearButton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::Button
     * @todo   Implement testButton().
     */
    public function testButton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::SenderButton
     * @todo   Implement testSenderButton().
     */
    public function testSenderButton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::submit
     * @todo   Implement testSubmit().
     */
    public function testSubmit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::addToForm
     * @todo   Implement testAddToForm().
     */
    public function testAddToForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getLastField
     * @todo   Implement testGetLastField().
     */
    public function testGetLastField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::addAction2Form
     * @todo   Implement testAddAction2Form().
     */
    public function testAddAction2Form() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::printable
     * @todo   Implement testPrintable().
     */
    public function testPrintable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::autoprint
     * @todo   Implement testAutoprint().
     */
    public function testAutoprint() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::omitir_cabecalho
     * @todo   Implement testOmitir_cabecalho().
     */
    public function testOmitir_cabecalho() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FormHelper::getFlush
     * @todo   Implement testGetFlush().
     */
    public function testGetFlush() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
