<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:15:05.
 */
class GenJsValidatorHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var GenJsValidatorHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GenJsValidatorHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GenJsValidatorHelper::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GenJsValidatorHelper::setForm
     * @todo   Implement testSetForm().
     */
    public function testSetForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GenJsValidatorHelper::addValidation
     * @todo   Implement testAddValidation().
     */
    public function testAddValidation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GenJsValidatorHelper::addMask
     * @todo   Implement testAddMask().
     */
    public function testAddMask() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GenJsValidatorHelper::genJs
     * @todo   Implement testGenJs().
     */
    public function testGenJs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GenJsValidatorHelper::sample
     * @todo   Implement testSample().
     */
    public function testSample() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
